spring.application.name=JWT

spring.datasource.url=jdbc:mysql://localhost:3306/rent_db?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=qwer1234
spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

security.jwt.secret_key=4eeab33d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
security.jwt.access_token_expiration=36000000 # 10 hours
security.jwt.refresh_token_expiration=252000000 # 7 days

